// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/yanoandri/yano-golang-training-beginner/model"
)

// IInquiriesService is an autogenerated mock type for the IInquiriesService type
type IInquiriesService struct {
	mock.Mock
}

// CreateInquiry provides a mock function with given fields: inquiry
func (_m *IInquiriesService) CreateInquiry(inquiry model.Inquiries) (model.Inquiries, error) {
	ret := _m.Called(inquiry)

	var r0 model.Inquiries
	if rf, ok := ret.Get(0).(func(model.Inquiries) model.Inquiries); ok {
		r0 = rf(inquiry)
	} else {
		r0 = ret.Get(0).(model.Inquiries)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Inquiries) error); ok {
		r1 = rf(inquiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInquiryByTransactionId provides a mock function with given fields: id
func (_m *IInquiriesService) GetInquiryByTransactionId(id string) (model.Inquiries, error) {
	ret := _m.Called(id)

	var r0 model.Inquiries
	if rf, ok := ret.Get(0).(func(string) model.Inquiries); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Inquiries)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
