// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/yanoandri/yano-golang-training-beginner/model"
)

// IPaymentsService is an autogenerated mock type for the IPaymentsService type
type IPaymentsService struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: payment
func (_m *IPaymentsService) CreatePayment(payment model.Payments) (model.Payments, error) {
	ret := _m.Called(payment)

	var r0 model.Payments
	if rf, ok := ret.Get(0).(func(model.Payments) model.Payments); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Get(0).(model.Payments)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Payments) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentById provides a mock function with given fields: id
func (_m *IPaymentsService) GetPaymentById(id string) (model.Payments, error) {
	ret := _m.Called(id)

	var r0 model.Payments
	if rf, ok := ret.Get(0).(func(string) model.Payments); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Payments)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
