// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigDB is an autogenerated mock type for the ConfigDB type
type ConfigDB struct {
	mock.Mock
}

// SetupDB provides a mock function with given fields:
func (_m *ConfigDB) SetupDB() {
	_m.Called()
}
